### ISSUE TITLE
Setup using initial password prompt does not work

### ISSUE THREAD

**Issue by rymndhng** [defunkt/gist.el#104] opened 2017-10-15 20:05 UTC
*Expected*: Setting up the plugin using the password prompt should save my Github OAuth Token. I should be able to create a gist.

*Actual*: Gists fails to create and I see the error message `helm-M-x: Driver has not been opened in read mode`.

What I've noticed is that the instructions in https://github.com/defunkt/gist.el#getting-started states that the password prompt should save the password to `.gitconfig`. I've observed that this isn't the case, and `gist.el` worked once I manually set the token using `git config --global github.oauth-token ..`.

**Comment by sigma** [comment] 2017-11-20 01:50
The error you see was due to a bug in `marshal.el` 0.8.0. It should be fixed in 0.8.2

I just went through a clean install and confirmed that generating and recording an oauth token the first time using password authentication worked.

Thanks !

**Closed by sigma** 2017-11-20 01:50 UTC
